WINDOW_SIZE = 1024
HOP_FRAC = 2
HOP_SIZE = WINDOW_SIZE/HOP_FRAC
SAMPLE_RATE = 22050
LOW_FREQ = 0
HIGH_FREQ = 11000
BANDS = 40
COEFS = 13
USE_GFCC = True
TIMBRE_GROUP = 'gfccs' if USE_GFCC else 'mfccs'
RHYTHM_GROUP = 'beat_coefs'
CHROMA_GROUP = 'chroma'
ISTFTM_ITER = 50


valid_data_types = set([TIMBRE_GROUP, RHYTHM_GROUP, CHROMA_GROUP])
